repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint src/*.py main.py tests/*.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
